export const GET_POKEMONS="GET_POKEMONS";
export const GET_TYPES="GET_TYPES";
export const GET_FROM="GET_FROM";
export const GET_POKEMON_NAME = "GET_POKEMON_NAME"
export const ERROR = "ERROR"
export const SET_PAGE = "SET_PAGE"
export const CHANGE_TYPE="CHANGE_TYPE"
export const ORDER_BY_ATTACK = "ORDER_BY_ATTACK"
export const ORDER_BY_NAME = "ORDER_BY_NAME"
export const FIND = "FIND"